language: node_js
node_js:
    - "5.5.0"

install:
    - npm install

before_script:
    - git config --global user.name 'ruanyl'
    - git config --global user.email 'ruanyu1@gmail.com'

script:
    - npm run deploy
